### ISSUE TITLE
Image resize post processing step

### ISSUE THREAD

**Issue by falkobuttler** [WeltN24/Carlos#110]
Thanks for this great component - using it in a Watch project. 

Could you please post an example of a post processing image cache step? In my case I'd like to resize the images after downloading. I'd also like to understand how I could conditionally do that based on the app state (in my case I only want to resize if the JSON property has a certain value).

**Comment by vittoriom** [comment]
Hi @falkobuttler,

with regards to your needs, assuming you already have an image resizing algorithm (if you don't, you can consider using `ImageIO` and [CGImageSourceCreateThumbnailAtIndex](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGImageSource/#//apple_ref/c/func/CGImageSourceCreateThumbnailAtIndex) - moreover, you can track #69 for an algorithm that will be directly included in Carlos in one of the next releases) you can do something like:

```swift
let cache = CacheProvider.imageCache().postProcess { image in
  myResizingAlgorithm.resize(image)
}
```

This snippet also assumes that you always want to resize images in the same way (that is, you don't want to do a "conditional resizing". For example, you could resize **all** images to a same thumbnail size).

If you want to conditionally do that, you can evaluate the condition in the `postProcess` transformation closure:

```swift
let cache = CacheProvider.imageCache().postProcess { image in
  if let shouldResize = json["shouldResize"] as? Bool where shouldResize == true {
    return myResizingAlgorithm.resize(image)
  } else {
    return image
  }
}
```

This assumes the JSON property you mentioned is available beforehand (if you don't, please consider extracting the condition evaluation to an external class/function that can have this information available) and not depending on the key you're fetching the image for (since this feature is not available in Carlos yet - please track #102 for this)

Would this work for you? If I didn't properly understand your use case, please elaborate more and I'll try to adapt my reply. :)

**Comment by falkobuttler** [comment]
Thank you very much @vittoriom. Your version didn't mention the return type, which is a bit confusing. Here is my final solution for your (and other peoples) reference:

    let cache = CacheProvider.imageCache().capRequests(3).postProcess { image in
        return Future(promise: Promise(value: UIImage.imageScaledToHeight(image, height: 35)))
    }

I think it would be beneficial to add this to the README file. I can't solve my second post-processing step  though, since I would have to know the key for the fetched image (I'll keep an eye on #102).

**Comment by vittoriom** [comment]
You're right, I blind-typed the code and forgot about the return type. If you don't mind, I would suggest you to use the short-hand version by calling `future` on the `Promise` instead:

```swift
let cache = CacheProvider.imageCache().capRequests(3).postProcess { image in
    return Promise(value: UIImage.imageScaledToHeight(image, height: 35)).future
}
```

I was thinking about making the `Future` initializer private, but I think it could be confusing to people who couldn't easily find the `future` property.

Moreover, I'm not sure how you store that cache afterwards, but keep in mind that `CacheProvider.imageCache()` always returns a new instance (I'll make it more clear in the `README` and add a new `shared***Cache` set of properties to `CacheProvider` in case one is interested - #111)

Regarding your need to conditionally post-process the image according to the key, I could suggest you another way.
Since every function you apply to a `CacheLevel` returns a new `CacheLevel` without modifying the previous one, you could create 2 caches (or it would be better to say, 2 views of the same cache): one that doesn't resize and one that does. Then, with the `switchLevels` function (that takes the `key` as a parameter), you could decide which "lane" to use. Under the hood, up to the post processing step, the very same levels (memory, disk, network) will be used, so they will share cached data. Then, the resizing could happen or not depending on which cache you returned in the `switchLevels` body. An example will clarify: 

```swift
// This is the "core" of the image cache
let simpleImageCache = CacheProvider.imageCache().capRequests(3)

/// On top of the core, you can resize "sometimes"
let postProcessingCache = simpleImageCache.postProcess { image in
    return Future(promise: Promise(value: UIImage.imageScaledToHeight(image, height: 35)))
}

let cache = switchLevels(simpleImageCache, postProcessingCache) { key in
  if /* key says full size */ {
    return .CacheA //First argument, simpleImageCache
  } else {
    return .CacheB //Second argument, postProcessingCache
  }
}
```

Keep in mind that `switchLevels` doesn't return a `BasicCache` so if you don't want to leak the implementation details and be free to further modify your cache in the future, you can call `normalize()` after `switchLevels` and you'll get a `BasicCache` back. This step is not needed, but could be useful for the future.

I think this will solve your second issue without waiting for #102 (since I already thought about that several times and didn't find an elegant solution, it could take a while before it's implemented).
Let me know if it works for you!

One more thing: if it's fine for you, I would like to include the name (and AppStore link) of your app in a new section of the readme about apps out there using Carlos. Let me know :)

I'd like to close the issue (or please do it yourself) if the proposed solution solves both your problems.

Thanks!

**Comment by falkobuttler** [comment]
Thanks, I got the resizing working properly as part of the cache now. Your recommendation for `switchLevel` doesn't work for me since I need to tint the image based on data for that particular object. I get JSON objects with icon urls and some of them also provide a color. I'll tint the images after I receive them from the cache for now.

**Comment by vittoriom** [comment]
Sorry to hear that, I didn't know about this image tinting need!
I'll try to find a way to do conditional post-processing the right way and post back here when it will be ready.

**Comment by vittoriom** [comment]
Hi @falkobuttler 
please checkout the latest `master` if you still need to conditionally post-process images depending on the key used to fetch the value:

```swift
let cache = myCache.conditionedPostProcess { (key, value) in 
   //You can inspect the key to determine what kind of post-processing you need
   return Promise(value: processedValue).future
}
```

**Comment by vittoriom** [comment]
Closing since I assume this is working fine now

**Comment by falkobuttler** [comment]
@vittoriom Thanks for making these changes. It is working flawlessly for me and I was able to remove all of my hacks I had in place!
