### ISSUE TITLE
Build error by Carthage

### ISSUE THREAD

**Issue by rizumita** [WeltN24/Carlos#114]
I tried building by Carthage and received the following error.

```
Undefined symbols for architecture x86_64:
  "direct type metadata for ext.Carlos.__ObjC.NSDateFormatter.Error", referenced from:
      protocol witness for Swift.ErrorType._domain.getter : Swift.String in conformance ext.Carlos.__ObjC.NSDateFormatter.Error : Swift.ErrorType in Carlos in ConcurrentOperation.o
  "direct type metadata for ext.Carlos.__ObjC.NSNumberFormatter.Error", referenced from:
      protocol witness for Swift.ErrorType._domain.getter : Swift.String in conformance ext.Carlos.__ObjC.NSNumberFormatter.Error : Swift.ErrorType in Carlos in ConcurrentOperation.o
ld: symbol(s) not found for architecture x86_64
```

By CocoaPods, Building succeeded.

**Comment by vittoriom** [comment]
Thanks for reporting, I should have been more careful with `Carthage`! I'm having some issues finding the reason to this failure, it looks like it's related to the `ConcurrentOperation` class (it still happens, with a different error message, if I remove the `NSDateFormatter` and `NSNumberFormatter` extensions), but as you noticed it only happens when building with `Carthage` and not when using `CocoaPods` or directly building from the source. 
I'll need some more time for this, hopefully you can still use `Carlos`, or do you need `Carthage`?

**Comment by rizumita** [comment]
No, I need Carthage.
Now, I'm using Carlos installed by CocoaPods.

**Comment by minhoryang** [comment]
+1 please consider carthage. I haven't used CocoaPods yet.

**Comment by minhoryang** [comment]
@rizumita Hey! try to use this!
```cartfile
github "minhoryang/Carlos" "carthage-optimization-disabled"
```

**Comment by vittoriom** [comment]
Thanks to @minhoryang the issue with `Carthage` should be fixed now on `master`!
