### ISSUE TITLE
How to get a specific cache level provided data requested

### ISSUE THREAD

**Issue by rizumita** [WeltN24/Carlos#117]
I want to know which cache level provided data I requested.
If memory or disk cache provided the data, I request JSON to an API server.
But if network cache provided, I want not to request to the server.
How do I this?

**Comment by vittoriom** [comment]
Hi @rizumita 
I'm not sure I get your use case, but this is what comes to my mind (I assume the cache takes a `NSURL` and returns a `AnyObject` (JSON))

```swift
let firstCache = (MemoryCacheLevel<NSURL, NSData>() >>> DiskCacheLevel()).postProcess { value in
    //Do your network request here...
    print("I did something here!")
    return Promise(value: value).future //Here we return the unmodified fetched value
}

//We chain our processed cache to a pooled network cache (you always want to pool network requests)
//Then we chain a JSON transformer so we don't get raw NSData back but a AnyObject
let chainedCache = (firstCache >>> (NetworkFetcher().pooled())) =>> JSONTransformer()
    
print("First request...")
chainedCache.get(NSURL(string: "http://google.com")!)
    
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(2 * Double(NSEC_PER_SEC))), dispatch_get_main_queue()) {
    print("second request...")
    chainedCache.get(NSURL(string: "http://google.com")!)
}
```

This outputs:
```
First request...
[Carlos][Debug]: Failed fetching http://google.com on the memory cache
[Carlos][Debug]: Failed fetching http://google.com on the disk cache
[Carlos][Debug]: Creating a new request Carlos.Future<NSData> for key http://google.com
[Carlos][Debug]: Fetched http://google.com from the network fetcher
[Carlos][Debug]: Setting a value for the key http://google.com on the memory cache Carlos.MemoryCacheLevel<NSURL, NSData>
[Carlos][Debug]: Setting a value for the key http://google.com on the disk cache Carlos.DiskCacheLevel<NSURL, NSData>
second request...
I did something here!
[Carlos][Debug]: Fetched http://google.com on memory level
```

The code would differ a bit if you actually want to return the JSON from the API in case the request hits the memory or disk, but I think this would actually need a different cache structure and I'll wait for your reply to understand more about the scenario.

Basically you can first group the memory and disk cache levels and attach a post processing step that makes the API request. Then you can chain this whole composed cache to a network level. 
This means that if a request succeeds from the memory or disk level, the post processing will kick in, otherwise it won't. What I'm not sure is whether you want to use the JSON returned by the API as a result of the fetch or it's just a side-effect of the request? Also, should these network requests go through a cache as well? Should they be pooled?
Of course if you make a request and that goes to the network, the next time you do the same request it will hit the memory cache, thus also triggering an API request (that's why I'm not sure I get your use case), but I guess this is fine for you?

Please elaborate more on your use case if the scenario I depicted doesn't fit your needs. 
Thanks!

**Comment by vittoriom** [comment]
I'll mark this as solved due to inactivity. Please reopen if it's still an issue

**Comment by rizumita** [comment]
@vittoriom 
Oh, I'm sorry to forget replying to your answer.
It became very helpful. Thank you!
