### ISSUE TITLE
For some caches `set` method is asynchronous, while there is no completion block for it and no `Future` is returned

### ISSUE THREAD

**Issue by explicitcall** [WeltN24/Carlos#121]
For `DiskCacheLevel` documentation on `set` method says 

>  Asynchronously sets a value for the given key

At the same time, there is no way to pass a completion block or to track a returned future status.

The main use-case, for example, is to know when the cache is fully persisted on disk or to set `onFailure` closure to track if anything failed during the disk write.

Is there a simple way to modify `set` API or to introduce something new that makes it possible to track the write progress?

**Comment by vittoriom** [comment]
Hi, IMHO from a high level point of view one doesn't need to know whether setting a value on a `CacheLevel` succeeded or not, since a cache doesn't have strict availability requirements, even when it's a persistent cache.
After all, what would you do if the `set` call fails?

Nonetheless, it should be relatively easy to change the `set` function to return a `Future<Bool>` and to implement the change in all the included `CacheLevel`s. The question is whether it's worth or not.

**Comment by explicitcall** [comment]
It would be quite useful to know why the write failed, so that it would be possible, for example, to let user know that storage is full and ask for cleanup if that was the reason, or to start running automatic cleanup immediately.

I don't think implementing this would conflict with availability requirements, it can be seen as a helper. If something fails, it's always useful to know why.
