### ISSUE TITLE
On success, failure or cancelation of a Promise clear all the listeners, not only the interested ones

### ISSUE THREAD

**Issue by vittoriom** [WeltN24/Carlos#130]
This should avoid undesired memory leaks

- [x] Implement fix
- [x] Write tests
- [x] Update CHANGELOG
- [x] Update Github milestone

**Comment by bkase** [comment]
FYI -- the source of the leak is a retain cycle between Future and Promise. Since `lazy var future` stores a `Future` and `Future` stores the `Promise`.

A simple fix is to change the `lazy var` to a getter (only downside is that you create a future per call to the getter, but a future has little overhead)

Carlos is awesome by the way

See:
https://github.com/mathcamp/Carlos/commit/e25e66c96173e1a549d861ecd1fd44ac481452fb

**Comment by vittoriom** [comment]
Hi @bkase,

well I guess you're totally right, I somehow overlooked that!

Your proposed change would work, I wonder what would happen if instead of returning a new value everytime, I use a lazy weak var instead. This way, it should only create a new `Future` if no one is using one that was already generated before. 

I'll try that out one of these days, but definitely thanks for noticing that!

**Comment by bkase** [comment]
`lazy weak var` is a good idea -- nice!
