### ISSUE TITLE
How do I show progress view during fetching by NetworkFetcher?

### ISSUE THREAD

**Issue by rizumita** [WeltN24/Carlos#131]
I want to show a progress view during fetching by NetworkFetcher.
How do I inject showing progress view process into NetworkFetcher process?

**Comment by vittoriom** [comment]
Hi @rizumita, thanks for reaching out! 

`NetworkFetcher` is internally using `NSURLSession` that apparently comes with no `NSProgress` support out of the box. 
Since what it does is just waiting for the completion handler to be called, there is no immediate solution to add a progress listener to the `NetworkFetcher` as of now. 
I assume the only solution would be to write another fetcher, more specific to your scenario, that for simplicity could even leverage Alamofire or another networking library that may come with progress support.

**Comment by rizumita** [comment]
Hi @vittoriom.

I'll create another fetcher. Thank you for reply.
