### ISSUE TITLE
Depend on mature Result library?

### ISSUE THREAD

**Issue by bkase** [WeltN24/Carlos#149]
Why not depend on a mature Result library rather than creating a Result from scratch?

see https://github.com/antitypical/Result

**Comment by vittoriom** [comment]
Hi @bkase!

At the time we created Carlos, we decided to use as few dependencies as possible, and we find that the usage of `Result` doesn't require a dependency at the moment. 

As you can see in #141, our implementation of `Result` is going to be improved anyway.

Moreover, the implementation you suggested is generic on 2 parameters (that is, it's also generic on the error type). This would cause quite a complication in `Carlos` API because of the transformations that an user can do to `CacheLevel`s, `Fetcher`s and so on.

If you have any specific feature request you would like to have on `Result`, don't hesitate to write it here!

**Comment by bkase** [comment]
Hi @vittoriom,

That makes sense -- thanks for the explanation.

This is obviously a much different question -- but what is the reasoning around not making the Promises, Result, Futures generic on the error type as well?

**Comment by vittoriom** [comment]
Hi @bkase, we decided not to make `Result`, `Promise` and `Future` generic on the error type because that would complicate things when it comes to the manipulation capabilities of `Carlos`.
Think for example at the `CacheLevel` composition and transformation functions. They would have to force `CacheLevel`s to match not only the stored type, but the error types too. 
We thought that would make these functions almost useless, so we opted for a "weaker" error management system.
