### ISSUE TITLE
Reify batchGetAll into a CacheLevel

### ISSUE THREAD

**Issue by bkase** [WeltN24/Carlos#154]
`cache.allBatch().get(ks)` is equivalent to `cache.batchGetAll(ks)`, but the former allows for composition with other cache levels (something I needed)

Please advise on naming

Reifying `batchGetSome` will require adding a `.some()` function to `PiedPiper` in addition to `.merge()` which I would be happy to do if you feel it would be worth it.

Thanks!

**Comment by vittoriom** [comment]
Hi @bkase, thanks for your contribution! 
I like the idea of having a "BatchAll" `CacheLevel` rather than just the method as it is right now.

If you already know how to proceed with the `Some` counterpart, feel free to start working on it, I think it would be a good improvement to the API!

Thanks again, I'll have a look at the PR now
