### ISSUE TITLE
Force to fetch from networking always

### ISSUE THREAD

**Issue by pietrocaselani** [WeltN24/Carlos#173]
I have the following code to fetch movies from networking and then cache it on memory and disk

```swift
let cache = MemoryCacheLevel<Movies, NSData>()
        .compose(DiskCacheLevel<Movies, NSData>())
        .compose(MoyaFetcher(provider: moviesProvider))
        .transformValues(JSONObjectTransfomer<Movie>())
```

but I need to always fetch from `MoyaFetcher` (is like `NetworkFetcher`).
There is a way to do this?

**Comment by vittoriom** [comment]
Hi @pietrocaselani, can you elaborate a bit more on your use case?

Why do you want to always fetch, if you have Disk and Memory cache in your setup? 
If you want to always fetch and ignore disk and memory, you can just instantiate the MoyaFetcher without composing it with the other cache levels.

**Comment by pietrocaselani** [comment]
@vittoriom I want to save in memory and disk cache for offline support, for example, but if there is an active connection, I want to fetch from API.
So that way, I can display information right away (from memory or disk), and then fetch updated info on API.

I think I can do this using RxSwift, but if there is a way to do this with Carlos, that would be great.

**Comment by vittoriom** [comment]
Oh, I see.

I think there is an immediate answer, and a proper answer:

The immediate answer is that you can fetch from memory/disk when offline, and network when online, very easily: you can use a switched cache and check for internet reachability in the switch condition. The code would be something like (I didn't compile this code so take it with a grain of salt):

```
let offlineLane = MemoryCacheLevel<Movies, NSData>()
        .compose(DiskCacheLevel<Movies, NSData>())
let onlineLane = offlineLane
        .compose(MoyaFetcher(provider: moviesProvider))

let switched = switchLevels(offlineLane, onlineLane) { key in
  return offline ? .cacheA : .cacheB
}

let cache = switched
        .transformValues(JSONObjectTransfomer<Movie>())
```

The proper answer is that the previous answer means you will have to wait for the network request when you're online, even if you have something stored in the memory or disk cache. 
This is because Carlos only deals with Futures and not reactive Signals. Thus, if a request is fulfilled with a value (say, something stored in the memory level), it can't be "refreshed" with a second one (which would be the one fetched from the network).

So if the first option is feasible for you, go for it.
If you want to immediately use the memory value but also fetch from the network and update the value with the latest one, you have to apply some reactive workaround.

**Comment by pietrocaselani** [comment]
@vittoriom I will handle this using RxSwift for now, but thanks for the quick answer!
